@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package icu.takeneko.nekoplus.foundation.recipes;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;