@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package icu.takeneko.nekoplus.internal;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;