@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package icu.takeneko.highenergyanvilology.block.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;