@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package icu.takeneko.highenergyanvilology.internal;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;