@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package icu.takeneko.highenergyanvilology.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;