@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package icu.takeneko.highenergyanvilology.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;