@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package icu.takeneko.highenergyanvilology.client.renderer.tesr;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;